<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="construction.xsl"?>
<!DOCTYPE labours
[
    <!ELEMENT labours (slot+)>
    <!ELEMENT slot (startDate,endDate,address,contractors?,workers+,equipment+,supply+)>
    <!ELEMENT startDate (#PCDATA)>
    <!ELEMENT endDate (#PCDATA)>
    <!ELEMENT address (street,city,region,country)>
    <!ELEMENT street (#PCDATA)>
    <!ELEMENT city (#PCDATA)>
    <!ELEMENT region (#PCDATA)>
    <!ELEMENT country (#PCDATA)>
    <!ELEMENT contractors (name)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT workers (firstName,lastName,role)>
    <!ELEMENT firstName (#PCDATA)>
    <!ELEMENT lastName (#PCDATA)>
    <!ELEMENT role (#PCDATA)>
    <!ELEMENT equipment (type,qty)>
    <!ELEMENT type (#PCDATA)>
    <!ELEMENT qty (#PCDATA)>
    <!ELEMENT supply (material,qty)>
    <!ELEMENT material (#PCDATA)>
    

]>
<labours>
  <slot>
    <startDate>2007-08-19</startDate>
    <endDate>2018-01-19</endDate>
    <address>
      <street>48 Rusk Street</street>
      <city>La Plaine-Saint-Denis</city>
      <region>Île-de-France</region>
      <country>France</country>
    </address>
    <workers>
      <firstName>Tiffany</firstName>
      <lastName>Strachan</lastName>
      <role>Supervisor</role>
    </workers>
    <workers>
      <firstName>Desirae</firstName>
      <lastName>Bryett</lastName>
      <role>Surveyor</role>
    </workers>
    <equipment>
      <type>Skid-Steer</type>
      <qty>9</qty>
    </equipment>
    <equipment>
      <type>Scraper</type>
      <qty>6</qty>
    </equipment>
    <equipment>
      <type>Dragline</type>
      <qty>10</qty>
    </equipment>
    <supply>
      <material>Steel</material>
      <qty>6</qty>
    </supply>
    <supply>
      <material>Granite</material>
      <qty>2</qty>
    </supply>
    <supply>
      <material>Vinyl</material>
      <qty>1</qty>
    </supply>
    <supply>
      <material>Brass</material>
      <qty>1</qty>
    </supply>
  </slot>
  <slot>
    <startDate>2006-09-02</startDate>
    <endDate>2012-04-01</endDate>
    <address>
      <street>30279 Bobwhite Court</street>
      <city>Saint-Lin-Laurentides</city>
      <region>Québec</region>
      <country>Canada</country>
    </address>
    <contractors>
      <name>Fahey-Leffler</name>
    </contractors>
    <workers>
      <firstName>Wain</firstName>
      <lastName>Leonards</lastName>
      <role>Construction Worker</role>
    </workers>
    <workers>
      <firstName>Traver</firstName>
      <lastName>Thiolier</lastName>
      <role>Project Manager</role>
    </workers>
    <equipment>
      <type>Excavator</type>
      <qty>0</qty>
    </equipment>
    <equipment>
      <type>Excavator</type>
      <qty>10</qty>
    </equipment>
    <equipment>
      <type>Dragline</type>
      <qty>0</qty>
    </equipment>
    <supply>
      <material>Glass</material>
      <qty>1</qty>
    </supply>
    <supply>
      <material>Plastic</material>
      <qty>8</qty>
    </supply>
    <supply>
      <material>Vinyl</material>
      <qty>7</qty>
    </supply>
    <supply>
      <material>Plexiglass</material>
      <qty>7</qty>
    </supply>
  </slot>
  <slot>
    <startDate>2005-01-27</startDate>
    <endDate>2018-02-15</endDate>
    <address>
      <street>46 Ohio Street</street>
      <city>Charlotte</city>
      <region>North Carolina</region>
      <country>United States</country>
    </address>
    <contractors>
      <name>Gutmann-slote</name>
    </contractors>
    <workers>
      <firstName>Manfred</firstName>
      <lastName>Lamden</lastName>
      <role>Construction Manager</role>
    </workers>
    <workers>
      <firstName>Patty</firstName>
      <lastName>Bridell</lastName>
      <role>Construction Expeditor</role>
    </workers>
    <equipment>
      <type>Grader</type>
      <qty>2</qty>
    </equipment>
    <equipment>
      <type>Backhoe</type>
      <qty>3</qty>
    </equipment>
    <equipment>
      <type>Dump Truck</type>
      <qty>8</qty>
    </equipment>
    <supply>
      <material>Aluminum</material>
      <qty>5</qty>
    </supply>
    <supply>
      <material>Stone</material>
      <qty>3</qty>
    </supply>
    <supply>
      <material>Granite</material>
      <qty>2</qty>
    </supply>
    <supply>
      <material>Rubber</material>
      <qty>8</qty>
    </supply>
  </slot>
  <slot>
    <startDate>2006-06-26</startDate>
    <endDate>2024-06-28</endDate>
    <address>
      <street>18 Karstens Hill</street>
      <city>Honolulu</city>
      <region>Hawaii</region>
      <country>United States</country>
    </address>
    <contractors>
      <name>Wisoky Inc</name>
    </contractors>
    <workers>
      <firstName>Shina</firstName>
      <lastName>Blowfelde</lastName>
      <role>Engineer</role>
    </workers>
    <workers>
      <firstName>Fredericka</firstName>
      <lastName>Batters</lastName>
      <role>Project Manager</role>
    </workers>
    <equipment>
      <type>Grader</type>
      <qty>0</qty>
    </equipment>
    <equipment>
      <type>Scraper</type>
      <qty>5</qty>
    </equipment>
    <equipment>
      <type>Excavator</type>
      <qty>0</qty>
    </equipment>
    <supply>
      <material>Rubber</material>
      <qty>0</qty>
    </supply>
    <supply>
      <material>Vinyl</material>
      <qty>7</qty>
    </supply>
    <supply>
      <material>Stone</material>
      <qty>0</qty>
    </supply>
    <supply>
      <material>Wood</material>
      <qty>6</qty>
    </supply>
  </slot>
  <slot>
    <startDate>2007-02-22</startDate>
    <endDate>2022-09-10</endDate>
    <address>
      <street>9929 Gale Court</street>
      <city>Saint-Étienne</city>
      <region>Rhône-Alpes</region>
      <country>France</country>
    </address>
    <workers>
      <firstName>Lesly</firstName>
      <lastName>Moylane</lastName>
      <role>Construction Worker</role>
    </workers>
    <workers>
      <firstName>Gayleen</firstName>
      <lastName>Hubbucks</lastName>
      <role>Electrician</role>
    </workers>
    <equipment>
      <type>Scraper</type>
      <qty>1</qty>
    </equipment>
    <equipment>
      <type>Compactor</type>
      <qty>2</qty>
    </equipment>
    <equipment>
      <type>Scraper</type>
      <qty>9</qty>
    </equipment>
    <supply>
      <material>Aluminum</material>
      <qty>0</qty>
    </supply>
    <supply>
      <material>Granite</material>
      <qty>8</qty>
    </supply>
    <supply>
      <material>Plexiglass</material>
      <qty>2</qty>
    </supply>
    <supply>
      <material>Granite</material>
      <qty>6</qty>
    </supply>
  </slot>
  <slot>
    <startDate>2007-09-24</startDate>
    <endDate>2025-03-15</endDate>
    <address>
      <street>4 Fairfield Terrace</street>
      <city>Pasadena</city>
      <region>California</region>
      <country>United States</country>
    </address>
    <contractors>
      <name>Koepp-O'Connell</name>
    </contractors>
    <workers>
      <firstName>Evan</firstName>
      <lastName>Byrom</lastName>
      <role>Engineer</role>
    </workers>
    <workers>
      <firstName>Trey</firstName>
      <lastName>Whistlecroft</lastName>
      <role>Supervisor</role>
    </workers>
    <equipment>
      <type>Dragline</type>
      <qty>3</qty>
    </equipment>
    <equipment>
      <type>Scraper</type>
      <qty>3</qty>
    </equipment>
    <equipment>
      <type>Dump Truck</type>
      <qty>1</qty>
    </equipment>
    <supply>
      <material>Plastic</material>
      <qty>7</qty>
    </supply>
    <supply>
      <material>Plexiglass</material>
      <qty>3</qty>
    </supply>
    <supply>
      <material>Glass</material>
      <qty>6</qty>
    </supply>
    <supply>
      <material>Plexiglass</material>
      <qty>6</qty>
    </supply>
  </slot>
  <slot>
    <startDate>2005-09-12</startDate>
    <endDate>2011-11-18</endDate>
    <address>
      <street>11 Luster Crossing</street>
      <city>Paris 17</city>
      <region>Île-de-France</region>
      <country>France</country>
    </address>
    <workers>
      <firstName>Meade</firstName>
      <lastName>Gatiss</lastName>
      <role>Electrician</role>
    </workers>
    <workers>
      <firstName>Loralie</firstName>
      <lastName>Brocklebank</lastName>
      <role>Engineer</role>
    </workers>
    <equipment>
      <type>Dump Truck</type>
      <qty>7</qty>
    </equipment>
    <equipment>
      <type>Scraper</type>
      <qty>2</qty>
    </equipment>
    <equipment>
      <type>Bulldozer</type>
      <qty>2</qty>
    </equipment>
    <supply>
      <material>Granite</material>
      <qty>0</qty>
    </supply>
    <supply>
      <material>Glass</material>
      <qty>8</qty>
    </supply>
    <supply>
      <material>Wood</material>
      <qty>10</qty>
    </supply>
    <supply>
      <material>Granite</material>
      <qty>7</qty>
    </supply>
  </slot>
  <slot>
    <startDate>2006-05-06</startDate>
    <endDate>2029-05-09</endDate>
    <address>
      <street>6851 Mcguire Circle</street>
      <city>Marystown</city>
      <region>Newfoundland and Labrador</region>
      <country>Canada</country>
    </address>
    <contractors>
      <name>Flatley, Fritsch and Kshlerin</name>
    </contractors>
    <workers>
      <firstName>Barnie</firstName>
      <lastName>Chominski</lastName>
      <role>Estimator</role>
    </workers>
    <workers>
      <firstName>Ricky</firstName>
      <lastName>Kidstone</lastName>
      <role>Architect</role>
    </workers>
    <equipment>
      <type>Skid-Steer</type>
      <qty>8</qty>
    </equipment>
    <equipment>
      <type>Compactor</type>
      <qty>2</qty>
    </equipment>
    <equipment>
      <type>Backhoe</type>
      <qty>6</qty>
    </equipment>
    <supply>
      <material>Wood</material>
      <qty>5</qty>
    </supply>
    <supply>
      <material>Glass</material>
      <qty>1</qty>
    </supply>
    <supply>
      <material>Aluminum</material>
      <qty>7</qty>
    </supply>
    <supply>
      <material>Glass</material>
      <qty>8</qty>
    </supply>
  </slot>
  <slot>
    <startDate>2005-04-14</startDate>
    <endDate>2012-08-08</endDate>
    <address>
      <street>05 Knutson Junction</street>
      <city>Chicago</city>
      <region>Illinois</region>
      <country>United States</country>
    </address>
    <contractors>
      <name>Carroll, Dickinson and Kassulke</name>
    </contractors>
    <workers>
      <firstName>Thorny</firstName>
      <lastName>Keuntje</lastName>
      <role>Construction Expeditor</role>
    </workers>
    <workers>
      <firstName>Edi</firstName>
      <lastName>Kubicki</lastName>
      <role>Electrician</role>
    </workers>
    <equipment>
      <type>Bulldozer</type>
      <qty>4</qty>
    </equipment>
    <equipment>
      <type>Bulldozer</type>
      <qty>7</qty>
    </equipment>
    <equipment>
      <type>Bulldozer</type>
      <qty>1</qty>
    </equipment>
    <supply>
      <material>Aluminum</material>
      <qty>9</qty>
    </supply>
    <supply>
      <material>Glass</material>
      <qty>1</qty>
    </supply>
    <supply>
      <material>Glass</material>
      <qty>8</qty>
    </supply>
    <supply>
      <material>Granite</material>
      <qty>7</qty>
    </supply>
  </slot>
  <slot>
    <startDate>2009-01-14</startDate>
    <endDate>2017-05-24</endDate>
    <address>
      <street>9796 Delladonna Circle</street>
      <city>Killarney</city>
      <region>Manitoba</region>
      <country>Canada</country>
    </address>
    <contractors>
      <name>Stiedemann-Feeney</name>
    </contractors>
    <workers>
      <firstName>Prisca</firstName>
      <lastName>Kubat</lastName>
      <role>Construction Foreman</role>
    </workers>
    <workers>
      <firstName>Ricki</firstName>
      <lastName>Critcher</lastName>
      <role>Supervisor</role>
    </workers>
    <equipment>
      <type>Grader</type>
      <qty>8</qty>
    </equipment>
    <equipment>
      <type>Compactor</type>
      <qty>8</qty>
    </equipment>
    <equipment>
      <type>Grader</type>
      <qty>1</qty>
    </equipment>
    <supply>
      <material>Plexiglass</material>
      <qty>1</qty>
    </supply>
    <supply>
      <material>Stone</material>
      <qty>2</qty>
    </supply>
    <supply>
      <material>Granite</material>
      <qty>10</qty>
    </supply>
    <supply>
      <material>Steel</material>
      <qty>3</qty>
    </supply>
  </slot>
  <slot>
    <startDate>2007-05-26</startDate>
    <endDate>2028-10-27</endDate>
    <address>
      <street>70436 Grover Plaza</street>
      <city>Bochum</city>
      <region>Nordrhein-Westfalen</region>
      <country>Germany</country>
    </address>
    <workers>
      <firstName>Odie</firstName>
      <lastName>Mikalski</lastName>
      <role>Supervisor</role>
    </workers>
    <workers>
      <firstName>Aymer</firstName>
      <lastName>Barhims</lastName>
      <role>Construction Expeditor</role>
    </workers>
    <equipment>
      <type>Dump Truck</type>
      <qty>9</qty>
    </equipment>
    <equipment>
      <type>Backhoe</type>
      <qty>0</qty>
    </equipment>
    <equipment>
      <type>Scraper</type>
      <qty>8</qty>
    </equipment>
    <supply>
      <material>Stone</material>
      <qty>9</qty>
    </supply>
    <supply>
      <material>Granite</material>
      <qty>2</qty>
    </supply>
    <supply>
      <material>Wood</material>
      <qty>0</qty>
    </supply>
    <supply>
      <material>Granite</material>
      <qty>8</qty>
    </supply>
  </slot>
  <slot>
    <startDate>2009-06-15</startDate>
    <endDate>2016-02-04</endDate>
    <address>
      <street>1 Arapahoe Center</street>
      <city>Dorchester</city>
      <region>Ontario</region>
      <country>Canada</country>
    </address>
    <workers>
      <firstName>Daniella</firstName>
      <lastName>Drysdell</lastName>
      <role>Project Manager</role>
    </workers>
    <workers>
      <firstName>Verne</firstName>
      <lastName>Boswood</lastName>
      <role>Supervisor</role>
    </workers>
    <equipment>
      <type>Dragline</type>
      <qty>7</qty>
    </equipment>
    <equipment>
      <type>Scraper</type>
      <qty>0</qty>
    </equipment>
    <equipment>
      <type>Skid-Steer</type>
      <qty>9</qty>
    </equipment>
    <supply>
      <material>Wood</material>
      <qty>3</qty>
    </supply>
    <supply>
      <material>Aluminum</material>
      <qty>9</qty>
    </supply>
    <supply>
      <material>Plexiglass</material>
      <qty>3</qty>
    </supply>
    <supply>
      <material>Rubber</material>
      <qty>3</qty>
    </supply>
  </slot>
  <slot>
    <startDate>2007-08-15</startDate>
    <endDate>2015-05-08</endDate>
    <address>
      <street>64 Lukken Hill</street>
      <city>Paris 15</city>
      <region>Île-de-France</region>
      <country>France</country>
    </address>
    <contractors>
      <name>Bednar-Orn</name>
    </contractors>
    <workers>
      <firstName>Barbaraanne</firstName>
      <lastName>Youel</lastName>
      <role>Construction Worker</role>
    </workers>
    <workers>
      <firstName>Guido</firstName>
      <lastName>Bertram</lastName>
      <role>Project Manager</role>
    </workers>
    <equipment>
      <type>Dragline</type>
      <qty>1</qty>
    </equipment>
    <equipment>
      <type>Skid-Steer</type>
      <qty>6</qty>
    </equipment>
    <equipment>
      <type>Compactor</type>
      <qty>4</qty>
    </equipment>
    <supply>
      <material>Rubber</material>
      <qty>0</qty>
    </supply>
    <supply>
      <material>Aluminum</material>
      <qty>8</qty>
    </supply>
    <supply>
      <material>Plexiglass</material>
      <qty>8</qty>
    </supply>
    <supply>
      <material>Vinyl</material>
      <qty>9</qty>
    </supply>
  </slot>
  <slot>
    <startDate>2005-10-21</startDate>
    <endDate>2010-11-06</endDate>
    <address>
      <street>25796 Hooker Circle</street>
      <city>Fullerton</city>
      <region>California</region>
      <country>United States</country>
    </address>
    <contractors>
      <name>Bednar, Kuhlman and Hyatt</name>
    </contractors>
    <workers>
      <firstName>Mureil</firstName>
      <lastName>Gerrill</lastName>
      <role>Supervisor</role>
    </workers>
    <workers>
      <firstName>Packston</firstName>
      <lastName>Bartens</lastName>
      <role>Project Manager</role>
    </workers>
    <equipment>
      <type>Compactor</type>
      <qty>4</qty>
    </equipment>
    <equipment>
      <type>Dump Truck</type>
      <qty>1</qty>
    </equipment>
    <equipment>
      <type>Skid-Steer</type>
      <qty>8</qty>
    </equipment>
    <supply>
      <material>Granite</material>
      <qty>6</qty>
    </supply>
    <supply>
      <material>Vinyl</material>
      <qty>3</qty>
    </supply>
    <supply>
      <material>Granite</material>
      <qty>6</qty>
    </supply>
    <supply>
      <material>Brass</material>
      <qty>1</qty>
    </supply>
  </slot>
  <slot>
    <startDate>2008-07-25</startDate>
    <endDate>2013-09-03</endDate>
    <address>
      <street>78894 Fordem Trail</street>
      <city>Rueil-Malmaison</city>
      <region>Île-de-France</region>
      <country>France</country>
    </address>
    <workers>
      <firstName>Brooks</firstName>
      <lastName>Yakubov</lastName>
      <role>Engineer</role>
    </workers>
    <workers>
      <firstName>Elysha</firstName>
      <lastName>Grandisson</lastName>
      <role>Supervisor</role>
    </workers>
    <equipment>
      <type>Dump Truck</type>
      <qty>8</qty>
    </equipment>
    <equipment>
      <type>Scraper</type>
      <qty>6</qty>
    </equipment>
    <equipment>
      <type>Dump Truck</type>
      <qty>4</qty>
    </equipment>
    <supply>
      <material>Rubber</material>
      <qty>4</qty>
    </supply>
    <supply>
      <material>Wood</material>
      <qty>5</qty>
    </supply>
    <supply>
      <material>Brass</material>
      <qty>7</qty>
    </supply>
    <supply>
      <material>Granite</material>
      <qty>0</qty>
    </supply>
  </slot>
</labours>