<?xml version = "1.0" encoding= "UTF-8"?>

<!DOCTYPE BussinessCards
[
<!ELEMENT BussinessCards (Person+)>
<!ELEMENT Person (Name, Phone+, Email)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Phone (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ATTLIST Phone id CDATA #REQUIRED>
]
>

<BussinessCards>
    <Person>
        <Name>Rorie Demanche</Name>
        <Phone id="home">+1 (710) 153-4949</Phone>   
        <Phone id="work">+1 (503) 319-3558</Phone>    
        <Phone id="mobile">+1 (182) 748-1667</Phone>
        <Email>rdemanche0@foxnews.com</Email>
    </Person>
    <Person>
        <Name>Kelcey Surman</Name>
        <Phone id="home">+1 (249) 926-7376</Phone>   
        <Phone id="work">+1 (208) 363-6588</Phone>    
        <Phone id="mobile">+1 (982) 536-6860</Phone>
        <Email>ksurman1@usnews.com</Email>
    </Person>
    <Person>
        <Name>Simon Heddan</Name>
        <Phone id="home">+1 (687) 808-4290</Phone>   
        <Phone id="work">+1 (604) 815-7810</Phone>    
        <Phone id="mobile">+1 (924) 174-3271</Phone>
        <Email>sheddan2@alexa.com</Email>
    </Person>
    <Person>
        <Name>Chan Supple</Name>
        <Phone id="home">+1 (577) 165-2495</Phone>   
        <Phone id="work">+1 (547) 934-7337</Phone>    
        <Phone id="mobile">+1 (367) 667-0747</Phone>
        <Email>csupple3@123-reg.co.uk</Email>
    </Person>
</BussinessCards>